data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  image_size: [224, 224]
  batch_size: 16  # Reduced for stability

model:
  architecture: "efficientnet_b3"
  num_classes: 4
  learning_rate: 0.001
  pretrained: true

training:
  epochs: 30  # Reduced for testing
  early_stopping_patience: 5
  validation_split: 0.2

classes:
  - "WSSV_BG"
  - "WSSV"
  - "Healthy"
  - "BG"